language: node_js
before_install:
- openssl aes-256-cbc -K $encrypted_9575438ce3f6_key -iv $encrypted_9575438ce3f6_iv -in aws-exports.js.enc -out src/aws-exports.js -d
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test